#version: '3'

services:

  python:
    build:
      context: ./python
    networks:
      - bermiotarra
    volumes:
      - /home/projects/bermiotarra:/app
      - ./logs/python:/app/logs

  deno:
    restart: always
    build:
      context: ./deno
    networks:
      - bermiotarra
    volumes:
      - /home/projects/bermiotarra:/app
      - ./logs/deno:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  caddy:
    restart: always
    build:
      context: ./caddy
    networks:
      - bermiotarra
    depends_on:
      - deno
    volumes:
      - /home/projects/bermiotarra:/app
      - ./logs/caddy:/var/log/caddy
    ports:
      - "8002:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bermiotarra:
    external: true
