server {
    listen 80;
    server_name bermiotarra.zital.eus bermiotarra.opi5;

    root /app/web/public;
    index index.html;

    location /search {
        proxy_pass   http://deno:8080/search;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    error_log  /dev/stderr error;
    access_log /dev/stdout;
}
